"""This example is based on github.com"""
import logging

import requests

from codedog.utils import init_local_logging

init_local_logging(level=logging.INFO)

# repository_name_or_id = "Arcadia822/codedog"
# pull_request_number = 2

server = "http://127.0.0.1:32167/v1/webhook/github"
event = """{
  "action": "opened",
  "number": 2,
  "pull_request": {
    "url": "https://api.github.com/repos/codedog-ai/codedog/pulls/2",
    "id": 1434434887,
    "node_id": "PR_kwDOJ7OMCM5Vf71H",
    "html_url": "https://github.com/codedog-ai/codedog/pull/2",
    "diff_url": "https://github.com/codedog-ai/codedog/pull/2.diff",
    "patch_url": "https://github.com/codedog-ai/codedog/pull/2.patch",
    "issue_url": "https://api.github.com/repos/codedog-ai/codedog/issues/2",
    "number": 2,
    "state": "open",
    "locked": false,
    "title": "feat(telemetry): :sparkles: collect gpt api cost",
    "user": {
      "login": "Arcadia822",
      "id": 19199644,
      "node_id": "MDQ6VXNlcjE5MTk5NjQ0",
      "avatar_url": "https://avatars.githubusercontent.com/u/19199644?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Arcadia822",
      "html_url": "https://github.com/Arcadia822",
      "followers_url": "https://api.github.com/users/Arcadia822/followers",
      "following_url": "https://api.github.com/users/Arcadia822/following{/other_user}",
      "gists_url": "https://api.github.com/users/Arcadia822/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Arcadia822/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Arcadia822/subscriptions",
      "organizations_url": "https://api.github.com/users/Arcadia822/orgs",
      "repos_url": "https://api.github.com/users/Arcadia822/repos",
      "events_url": "https://api.github.com/users/Arcadia822/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Arcadia822/received_events",
      "type": "User",
      "site_admin": false
    },
    "body": "collect GPT call cost from openai callback of langchain",
    "created_at": "2023-07-14T08:52:54Z",
    "updated_at": "2023-07-14T08:52:54Z",
    "closed_at": null,
    "merged_at": null,
    "merge_commit_sha": null,
    "assignee": null,
    "assignees": [

    ],
    "requested_reviewers": [

    ],
    "requested_teams": [

    ],
    "labels": [

    ],
    "milestone": null,
    "draft": false,
    "commits_url": "https://api.github.com/repos/codedog-ai/codedog/pulls/2/commits",
    "review_comments_url": "https://api.github.com/repos/codedog-ai/codedog/pulls/2/comments",
    "review_comment_url": "https://api.github.com/repos/codedog-ai/codedog/pulls/comments{/number}",
    "comments_url": "https://api.github.com/repos/codedog-ai/codedog/issues/2/comments",
    "statuses_url": "https://api.github.com/repos/codedog-ai/codedog/statuses/8ecfcf6d9a5dfccddf43fdc755b82046a7e5a710",
    "head": {
      "label": "codedog-ai:feature/openai-cost",
      "ref": "feature/openai-cost",
      "sha": "8ecfcf6d9a5dfccddf43fdc755b82046a7e5a710",
      "user": {
        "login": "codedog-ai",
        "id": 135947515,
        "node_id": "O_kgDOCBpk-w",
        "avatar_url": "https://avatars.githubusercontent.com/u/135947515?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/codedog-ai",
        "html_url": "https://github.com/codedog-ai",
        "followers_url": "https://api.github.com/users/codedog-ai/followers",
        "following_url": "https://api.github.com/users/codedog-ai/following{/other_user}",
        "gists_url": "https://api.github.com/users/codedog-ai/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/codedog-ai/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/codedog-ai/subscriptions",
        "organizations_url": "https://api.github.com/users/codedog-ai/orgs",
        "repos_url": "https://api.github.com/users/codedog-ai/repos",
        "events_url": "https://api.github.com/users/codedog-ai/events{/privacy}",
        "received_events_url": "https://api.github.com/users/codedog-ai/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "repo": {
        "id": 666078216,
        "node_id": "R_kgDOJ7OMCA",
        "name": "codedog",
        "full_name": "codedog-ai/codedog",
        "private": false,
        "owner": {
          "login": "codedog-ai",
          "id": 135947515,
          "node_id": "O_kgDOCBpk-w",
          "avatar_url": "https://avatars.githubusercontent.com/u/135947515?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/codedog-ai",
          "html_url": "https://github.com/codedog-ai",
          "followers_url": "https://api.github.com/users/codedog-ai/followers",
          "following_url": "https://api.github.com/users/codedog-ai/following{/other_user}",
          "gists_url": "https://api.github.com/users/codedog-ai/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/codedog-ai/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/codedog-ai/subscriptions",
          "organizations_url": "https://api.github.com/users/codedog-ai/orgs",
          "repos_url": "https://api.github.com/users/codedog-ai/repos",
          "events_url": "https://api.github.com/users/codedog-ai/events{/privacy}",
          "received_events_url": "https://api.github.com/users/codedog-ai/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "html_url": "https://github.com/codedog-ai/codedog",
        "description": "Code review powered by LLM",
        "fork": false,
        "url": "https://api.github.com/repos/codedog-ai/codedog",
        "forks_url": "https://api.github.com/repos/codedog-ai/codedog/forks",
        "keys_url": "https://api.github.com/repos/codedog-ai/codedog/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/codedog-ai/codedog/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/codedog-ai/codedog/teams",
        "hooks_url": "https://api.github.com/repos/codedog-ai/codedog/hooks",
        "issue_events_url": "https://api.github.com/repos/codedog-ai/codedog/issues/events{/number}",
        "events_url": "https://api.github.com/repos/codedog-ai/codedog/events",
        "assignees_url": "https://api.github.com/repos/codedog-ai/codedog/assignees{/user}",
        "branches_url": "https://api.github.com/repos/codedog-ai/codedog/branches{/branch}",
        "tags_url": "https://api.github.com/repos/codedog-ai/codedog/tags",
        "blobs_url": "https://api.github.com/repos/codedog-ai/codedog/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/codedog-ai/codedog/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/codedog-ai/codedog/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/codedog-ai/codedog/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/codedog-ai/codedog/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/codedog-ai/codedog/languages",
        "stargazers_url": "https://api.github.com/repos/codedog-ai/codedog/stargazers",
        "contributors_url": "https://api.github.com/repos/codedog-ai/codedog/contributors",
        "subscribers_url": "https://api.github.com/repos/codedog-ai/codedog/subscribers",
        "subscription_url": "https://api.github.com/repos/codedog-ai/codedog/subscription",
        "commits_url": "https://api.github.com/repos/codedog-ai/codedog/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/codedog-ai/codedog/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/codedog-ai/codedog/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/codedog-ai/codedog/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/codedog-ai/codedog/contents/{+path}",
        "compare_url": "https://api.github.com/repos/codedog-ai/codedog/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/codedog-ai/codedog/merges",
        "archive_url": "https://api.github.com/repos/codedog-ai/codedog/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/codedog-ai/codedog/downloads",
        "issues_url": "https://api.github.com/repos/codedog-ai/codedog/issues{/number}",
        "pulls_url": "https://api.github.com/repos/codedog-ai/codedog/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/codedog-ai/codedog/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/codedog-ai/codedog/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/codedog-ai/codedog/labels{/name}",
        "releases_url": "https://api.github.com/repos/codedog-ai/codedog/releases{/id}",
        "deployments_url": "https://api.github.com/repos/codedog-ai/codedog/deployments",
        "created_at": "2023-07-13T16:54:36Z",
        "updated_at": "2023-07-14T05:24:22Z",
        "pushed_at": "2023-07-14T08:52:55Z",
        "git_url": "git://github.com/codedog-ai/codedog.git",
        "ssh_url": "git@github.com:codedog-ai/codedog.git",
        "clone_url": "https://github.com/codedog-ai/codedog.git",
        "svn_url": "https://github.com/codedog-ai/codedog",
        "homepage": "https://www.codedog.ai",
        "size": 3362,
        "stargazers_count": 3,
        "watchers_count": 3,
        "language": "Python",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 2,
        "license": {
          "key": "mit",
          "name": "MIT License",
          "spdx_id": "MIT",
          "url": "https://api.github.com/licenses/mit",
          "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "code-review-bot",
          "langchain",
          "pull-request-review"
        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 2,
        "watchers": 3,
        "default_branch": "master",
        "allow_squash_merge": true,
        "allow_merge_commit": true,
        "allow_rebase_merge": true,
        "allow_auto_merge": false,
        "delete_branch_on_merge": false,
        "allow_update_branch": false,
        "use_squash_pr_title_as_default": false,
        "squash_merge_commit_message": "COMMIT_MESSAGES",
        "squash_merge_commit_title": "COMMIT_OR_PR_TITLE",
        "merge_commit_message": "PR_TITLE",
        "merge_commit_title": "MERGE_MESSAGE"
      }
    },
    "base": {
      "label": "codedog-ai:master",
      "ref": "master",
      "sha": "126d3a06866816c07aed6208f8c88d54c0caeeba",
      "user": {
        "login": "codedog-ai",
        "id": 135947515,
        "node_id": "O_kgDOCBpk-w",
        "avatar_url": "https://avatars.githubusercontent.com/u/135947515?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/codedog-ai",
        "html_url": "https://github.com/codedog-ai",
        "followers_url": "https://api.github.com/users/codedog-ai/followers",
        "following_url": "https://api.github.com/users/codedog-ai/following{/other_user}",
        "gists_url": "https://api.github.com/users/codedog-ai/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/codedog-ai/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/codedog-ai/subscriptions",
        "organizations_url": "https://api.github.com/users/codedog-ai/orgs",
        "repos_url": "https://api.github.com/users/codedog-ai/repos",
        "events_url": "https://api.github.com/users/codedog-ai/events{/privacy}",
        "received_events_url": "https://api.github.com/users/codedog-ai/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "repo": {
        "id": 666078216,
        "node_id": "R_kgDOJ7OMCA",
        "name": "codedog",
        "full_name": "codedog-ai/codedog",
        "private": false,
        "owner": {
          "login": "codedog-ai",
          "id": 135947515,
          "node_id": "O_kgDOCBpk-w",
          "avatar_url": "https://avatars.githubusercontent.com/u/135947515?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/codedog-ai",
          "html_url": "https://github.com/codedog-ai",
          "followers_url": "https://api.github.com/users/codedog-ai/followers",
          "following_url": "https://api.github.com/users/codedog-ai/following{/other_user}",
          "gists_url": "https://api.github.com/users/codedog-ai/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/codedog-ai/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/codedog-ai/subscriptions",
          "organizations_url": "https://api.github.com/users/codedog-ai/orgs",
          "repos_url": "https://api.github.com/users/codedog-ai/repos",
          "events_url": "https://api.github.com/users/codedog-ai/events{/privacy}",
          "received_events_url": "https://api.github.com/users/codedog-ai/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "html_url": "https://github.com/codedog-ai/codedog",
        "description": "Code review powered by LLM",
        "fork": false,
        "url": "https://api.github.com/repos/codedog-ai/codedog",
        "forks_url": "https://api.github.com/repos/codedog-ai/codedog/forks",
        "keys_url": "https://api.github.com/repos/codedog-ai/codedog/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/codedog-ai/codedog/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/codedog-ai/codedog/teams",
        "hooks_url": "https://api.github.com/repos/codedog-ai/codedog/hooks",
        "issue_events_url": "https://api.github.com/repos/codedog-ai/codedog/issues/events{/number}",
        "events_url": "https://api.github.com/repos/codedog-ai/codedog/events",
        "assignees_url": "https://api.github.com/repos/codedog-ai/codedog/assignees{/user}",
        "branches_url": "https://api.github.com/repos/codedog-ai/codedog/branches{/branch}",
        "tags_url": "https://api.github.com/repos/codedog-ai/codedog/tags",
        "blobs_url": "https://api.github.com/repos/codedog-ai/codedog/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/codedog-ai/codedog/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/codedog-ai/codedog/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/codedog-ai/codedog/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/codedog-ai/codedog/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/codedog-ai/codedog/languages",
        "stargazers_url": "https://api.github.com/repos/codedog-ai/codedog/stargazers",
        "contributors_url": "https://api.github.com/repos/codedog-ai/codedog/contributors",
        "subscribers_url": "https://api.github.com/repos/codedog-ai/codedog/subscribers",
        "subscription_url": "https://api.github.com/repos/codedog-ai/codedog/subscription",
        "commits_url": "https://api.github.com/repos/codedog-ai/codedog/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/codedog-ai/codedog/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/codedog-ai/codedog/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/codedog-ai/codedog/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/codedog-ai/codedog/contents/{+path}",
        "compare_url": "https://api.github.com/repos/codedog-ai/codedog/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/codedog-ai/codedog/merges",
        "archive_url": "https://api.github.com/repos/codedog-ai/codedog/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/codedog-ai/codedog/downloads",
        "issues_url": "https://api.github.com/repos/codedog-ai/codedog/issues{/number}",
        "pulls_url": "https://api.github.com/repos/codedog-ai/codedog/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/codedog-ai/codedog/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/codedog-ai/codedog/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/codedog-ai/codedog/labels{/name}",
        "releases_url": "https://api.github.com/repos/codedog-ai/codedog/releases{/id}",
        "deployments_url": "https://api.github.com/repos/codedog-ai/codedog/deployments",
        "created_at": "2023-07-13T16:54:36Z",
        "updated_at": "2023-07-14T05:24:22Z",
        "pushed_at": "2023-07-14T08:52:55Z",
        "git_url": "git://github.com/codedog-ai/codedog.git",
        "ssh_url": "git@github.com:codedog-ai/codedog.git",
        "clone_url": "https://github.com/codedog-ai/codedog.git",
        "svn_url": "https://github.com/codedog-ai/codedog",
        "homepage": "https://www.codedog.ai",
        "size": 3362,
        "stargazers_count": 3,
        "watchers_count": 3,
        "language": "Python",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 2,
        "license": {
          "key": "mit",
          "name": "MIT License",
          "spdx_id": "MIT",
          "url": "https://api.github.com/licenses/mit",
          "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "code-review-bot",
          "langchain",
          "pull-request-review"
        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 2,
        "watchers": 3,
        "default_branch": "master",
        "allow_squash_merge": true,
        "allow_merge_commit": true,
        "allow_rebase_merge": true,
        "allow_auto_merge": false,
        "delete_branch_on_merge": false,
        "allow_update_branch": false,
        "use_squash_pr_title_as_default": false,
        "squash_merge_commit_message": "COMMIT_MESSAGES",
        "squash_merge_commit_title": "COMMIT_OR_PR_TITLE",
        "merge_commit_message": "PR_TITLE",
        "merge_commit_title": "MERGE_MESSAGE"
      }
    },
    "_links": {
      "self": {
        "href": "https://api.github.com/repos/codedog-ai/codedog/pulls/2"
      },
      "html": {
        "href": "https://github.com/codedog-ai/codedog/pull/2"
      },
      "issue": {
        "href": "https://api.github.com/repos/codedog-ai/codedog/issues/2"
      },
      "comments": {
        "href": "https://api.github.com/repos/codedog-ai/codedog/issues/2/comments"
      },
      "review_comments": {
        "href": "https://api.github.com/repos/codedog-ai/codedog/pulls/2/comments"
      },
      "review_comment": {
        "href": "https://api.github.com/repos/codedog-ai/codedog/pulls/comments{/number}"
      },
      "commits": {
        "href": "https://api.github.com/repos/codedog-ai/codedog/pulls/2/commits"
      },
      "statuses": {
        "href": "https://api.github.com/repos/codedog-ai/codedog/statuses/8ecfcf6d9a5dfccddf43fdc755b82046a7e5a710"
      }
    },
    "author_association": "COLLABORATOR",
    "auto_merge": null,
    "active_lock_reason": null,
    "merged": false,
    "mergeable": null,
    "rebaseable": null,
    "mergeable_state": "unknown",
    "merged_by": null,
    "comments": 0,
    "review_comments": 0,
    "maintainer_can_modify": false,
    "commits": 1,
    "additions": 16,
    "deletions": 28,
    "changed_files": 1
  },
  "repository": {
    "id": 666078216,
    "node_id": "R_kgDOJ7OMCA",
    "name": "codedog",
    "full_name": "codedog-ai/codedog",
    "private": false,
    "owner": {
      "login": "codedog-ai",
      "id": 135947515,
      "node_id": "O_kgDOCBpk-w",
      "avatar_url": "https://avatars.githubusercontent.com/u/135947515?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/codedog-ai",
      "html_url": "https://github.com/codedog-ai",
      "followers_url": "https://api.github.com/users/codedog-ai/followers",
      "following_url": "https://api.github.com/users/codedog-ai/following{/other_user}",
      "gists_url": "https://api.github.com/users/codedog-ai/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/codedog-ai/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/codedog-ai/subscriptions",
      "organizations_url": "https://api.github.com/users/codedog-ai/orgs",
      "repos_url": "https://api.github.com/users/codedog-ai/repos",
      "events_url": "https://api.github.com/users/codedog-ai/events{/privacy}",
      "received_events_url": "https://api.github.com/users/codedog-ai/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/codedog-ai/codedog",
    "description": "Code review powered by LLM",
    "fork": false,
    "url": "https://api.github.com/repos/codedog-ai/codedog",
    "forks_url": "https://api.github.com/repos/codedog-ai/codedog/forks",
    "keys_url": "https://api.github.com/repos/codedog-ai/codedog/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/codedog-ai/codedog/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/codedog-ai/codedog/teams",
    "hooks_url": "https://api.github.com/repos/codedog-ai/codedog/hooks",
    "issue_events_url": "https://api.github.com/repos/codedog-ai/codedog/issues/events{/number}",
    "events_url": "https://api.github.com/repos/codedog-ai/codedog/events",
    "assignees_url": "https://api.github.com/repos/codedog-ai/codedog/assignees{/user}",
    "branches_url": "https://api.github.com/repos/codedog-ai/codedog/branches{/branch}",
    "tags_url": "https://api.github.com/repos/codedog-ai/codedog/tags",
    "blobs_url": "https://api.github.com/repos/codedog-ai/codedog/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/codedog-ai/codedog/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/codedog-ai/codedog/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/codedog-ai/codedog/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/codedog-ai/codedog/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/codedog-ai/codedog/languages",
    "stargazers_url": "https://api.github.com/repos/codedog-ai/codedog/stargazers",
    "contributors_url": "https://api.github.com/repos/codedog-ai/codedog/contributors",
    "subscribers_url": "https://api.github.com/repos/codedog-ai/codedog/subscribers",
    "subscription_url": "https://api.github.com/repos/codedog-ai/codedog/subscription",
    "commits_url": "https://api.github.com/repos/codedog-ai/codedog/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/codedog-ai/codedog/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/codedog-ai/codedog/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/codedog-ai/codedog/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/codedog-ai/codedog/contents/{+path}",
    "compare_url": "https://api.github.com/repos/codedog-ai/codedog/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/codedog-ai/codedog/merges",
    "archive_url": "https://api.github.com/repos/codedog-ai/codedog/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/codedog-ai/codedog/downloads",
    "issues_url": "https://api.github.com/repos/codedog-ai/codedog/issues{/number}",
    "pulls_url": "https://api.github.com/repos/codedog-ai/codedog/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/codedog-ai/codedog/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/codedog-ai/codedog/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/codedog-ai/codedog/labels{/name}",
    "releases_url": "https://api.github.com/repos/codedog-ai/codedog/releases{/id}",
    "deployments_url": "https://api.github.com/repos/codedog-ai/codedog/deployments",
    "created_at": "2023-07-13T16:54:36Z",
    "updated_at": "2023-07-14T05:24:22Z",
    "pushed_at": "2023-07-14T08:52:55Z",
    "git_url": "git://github.com/codedog-ai/codedog.git",
    "ssh_url": "git@github.com:codedog-ai/codedog.git",
    "clone_url": "https://github.com/codedog-ai/codedog.git",
    "svn_url": "https://github.com/codedog-ai/codedog",
    "homepage": "https://www.codedog.ai",
    "size": 3362,
    "stargazers_count": 3,
    "watchers_count": 3,
    "language": "Python",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 2,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit",
      "node_id": "MDc6TGljZW5zZTEz"
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "code-review-bot",
      "langchain",
      "pull-request-review"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 2,
    "watchers": 3,
    "default_branch": "master"
  },
  "organization": {
    "login": "codedog-ai",
    "id": 135947515,
    "node_id": "O_kgDOCBpk-w",
    "url": "https://api.github.com/orgs/codedog-ai",
    "repos_url": "https://api.github.com/orgs/codedog-ai/repos",
    "events_url": "https://api.github.com/orgs/codedog-ai/events",
    "hooks_url": "https://api.github.com/orgs/codedog-ai/hooks",
    "issues_url": "https://api.github.com/orgs/codedog-ai/issues",
    "members_url": "https://api.github.com/orgs/codedog-ai/members{/member}",
    "public_members_url": "https://api.github.com/orgs/codedog-ai/public_members{/member}",
    "avatar_url": "https://avatars.githubusercontent.com/u/135947515?v=4",
    "description": null
  },
  "sender": {
    "login": "Arcadia822",
    "id": 19199644,
    "node_id": "MDQ6VXNlcjE5MTk5NjQ0",
    "avatar_url": "https://avatars.githubusercontent.com/u/19199644?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Arcadia822",
    "html_url": "https://github.com/Arcadia822",
    "followers_url": "https://api.github.com/users/Arcadia822/followers",
    "following_url": "https://api.github.com/users/Arcadia822/following{/other_user}",
    "gists_url": "https://api.github.com/users/Arcadia822/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Arcadia822/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Arcadia822/subscriptions",
    "organizations_url": "https://api.github.com/users/Arcadia822/orgs",
    "repos_url": "https://api.github.com/users/Arcadia822/repos",
    "events_url": "https://api.github.com/users/Arcadia822/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Arcadia822/received_events",
    "type": "User",
    "site_admin": false
  }
}"""

requests.post(url=server, data=event, headers={"Content-Type": "application/json"})
