from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field

from codedog.models.diff import DiffContent
from codedog.models.pull_request import PullRequest
from codedog.models.repository import Repository


class ChangeStatus(str, Enum):
    """Git file change mode. https://git-scm.com/docs/diff-format"""

    addition = "A"
    """Addition of a file"""
    copy = "C"
    """Copy of a file into a new one"""
    deletion = "D"
    """Deletion of a file"""
    modified = "M"
    """Modification of the contents or mode of a file"""
    renaming = "R"
    """Renaming of a file"""
    type_change = "T"
    """Change in the type of the file (regular file, symbolic link or submodule)"""
    unmerged = "U"
    """File is unmerged (you must complete the merge before it can be committed)"""
    unknown = "X"
    """Unknown change type (most probably a bug, please report it)"""


class ChangeFile(BaseModel):
    """A changed file between two commit."""

    full_name: str = Field()
    """File name and path."""
    status: ChangeStatus = Field()
    """Change status. see more information in ChangeStatus."""
    pull_request_id: int = Field()
    """Id of pull request this change belongs to."""
    repository_id: int = Field()
    """Id of pull request target repository this change file belongs to."""
    source_repository_id: int = Field()
    """Id of pull request source repository this change file belongs to."""
    start_commit_id: str = Field()
    """Start commit id"""
    end_commit_id: str = Field()
    """End commit id"""

    name: str = Field(default="")
    """File name without path."""
    diff_url: str = Field(default="")
    """Url of this change file in pull request."""
    commit_url: str = Field(default="")
    """Url of this change file in end commit. If change file type is deleted, this will be none."""
    diff_content: DiffContent = Field(default="")
    """The diff content of this file."""
    score: Optional[int] = Field(default=None)
    """Similarity score for Change Mode: C, R, M. Ranged in 0-100. Might not exist."""

    pull_request: Optional[PullRequest] = Field(default=None, exclude=True)
    """Pull request object this change file belongs to."""
    repository: Optional[Repository] = Field(default=None, exclude=True)
    """Repository object this change file belongs to."""
    source_repository: Optional[Repository] = Field(default=None, exclude=True)
    """Source repository object this change file belongs to.""" ""
    _raw_object: Optional[object] = Field(default=None, exclude=True)
    """Raw object generated by client api of this change file."""
